# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKRxRjOJcUgvH8zG9xZ0uoUPnJ4G91RE
"""

# Install dependencies (only needed once per Colab session)
!pip install opencv-python pillow matplotlib numpy

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from PIL import Image

# Function to load image
def load_image(path):
  img = cv2.imread(path)
  return img

# Filters
def apply_grayscale(img):
  return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

def apply_blur(img, ksize=7):
  return cv2.GaussianBlur(img, (ksize, ksize), 0)

def apply_sharpen(img):
  kernel = np.array([[0,-1,0], [-1,5,-1], [0,-1,0]])
  return cv2.filter2D(img, -1, kernel)

def apply_edges(img):
  return cv2.Canny(img, 100, 200)

def adjust_brightness_contrast(img, brightness=30, contrast=30):
  return cv2.convertScaleAbs(img, alpha=1 + contrast/100, beta=brightness)

# Display helper
def show_image(img, cmap=None):
  if len(img.shape) == 2: # grayscale
      plt.imshow(img, cmap='gray')
  else:
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
  plt.axis('off')
  plt.show()

# Example usage
path = "/content/image.jpg" # upload an image to Colab first
img = load_image(path)

# Apply filters
gray = apply_grayscale(img)
blur = apply_blur(img)
sharp = apply_sharpen(img)
edges = apply_edges(img)
bright = adjust_brightness_contrast(img, brightness=50, contrast=50)


# Show results
show_image(img) # original
show_image(gray) # grayscale
show_image(blur) # blur
show_image(sharp) # sharpen
show_image(edges) # edges
show_image(bright) # brightness/contrast

"""### Uploading an image to Colab

YouYou can upload an image to your Colab session by:

1.  Clicking the **folder icon** on the left sidebar (Files).
2.  Clicking the **'Upload to session storage' icon** (looks like an upward arrow).
3.  Selecting your image file from your local machine.

Once uploaded, it will typically be available in the `/content/` directory.
"""

